### ISSUE TITLE
Anyone know how to fix this?

### ISSUE THREAD

**Issue by Lord-Klavier** [ArkanDash/Multi-Model-RVC-Inference#1]
All the dependencies have been downloaded, and hubert_base.pt has been placed in the "Multi-Model-RVC-Inference" folder. Upon running app.py, this error appeared:

Traceback (most recent call last):
  File "/Users/axelerikswenson/Desktop/Multi-Model-RVC-Inference/app.py", line 344, in <module>
    categories = load_model()
  File "/Users/axelerikswenson/Desktop/Multi-Model-RVC-Inference/app.py", line 125, in load_model
    with open(f"weights/{category_folder}/model_info.json", "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'weights/CATEGORY_FOLDER_PATH/model_info.json'
(base) axelerikswenson@Axels-MBP Multi-Model-RVC-Inference % 

Considering all the files have been downloaded / and not tampered with, I honestly have no clue what could be the issue. Anyone have any ideas?

**Comment by Lord-Klavier** [comment]
Edit: I replaced the placeholder model_info.json files and the folder_info.json file with the ones given in the download of your Genshin JP RVC models, here are some linked pictures: However, I am not sure if I (again) set them up wrong as this only caused another problem: 
<img width="1435" alt="Screen Shot 2023-07-10 at 10 09 52 PM" src="https://github.com/ArkanDash/Multi-Model-RVC-Inference/assets/139093998/13cb9b53-dc02-4e76-a100-7b261840057f">
<img width="1244" alt="Screen Shot 2023-07-10 at 10 04 53 PM" src="https://github.com/ArkanDash/Multi-Model-RVC-Inference/assets/139093998/af9327ab-5d08-4167-b4da-ec70402761df">

However, I am not sure if I (again) set them up wrong, as this only caused another problem: 
Now when I run Python app.py, it essentially claims that there is an issue with the file weights/{category_folder}/{character_name}/{model_name}  and states an invalid load key, 'v'.
I will post the full log below, but if you have any insight into this problem I would sincerely appreciate it. I am not someone who is overly familiar with things of this sort, so while the solution may be obvious to others, I am quite clearly missing it haha! Thanks, and I appreciate your help!

Log:
(base) axelerikswenson@Axels-MBP Multi-Model-RVC-Inference % python app.py
2023-07-10 21:55:11 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-07-10 21:55:11 | INFO | faiss.loader | Successfully loaded faiss with AVX2 support.
没有发现支持的N卡, 使用CPU进行推理
2023-07-10 21:55:11 | INFO | fairseq.tasks.hubert_pretraining | current directory is /Users/axelerikswenson/Desktop/Multi-Model-RVC-Inference
2023-07-10 21:55:11 | INFO | fairseq.tasks.hubert_pretraining | HubertPretrainingTask Config {'_name': 'hubert_pretraining', 'data': 'metadata', 'fine_tuning': False, 'labels': ['km'], 'label_dir': 'label', 'label_rate': 50.0, 'sample_rate': 16000, 'normalize': False, 'enable_padding': False, 'max_keep_size': None, 'max_sample_size': 250000, 'min_sample_size': 32000, 'single_target': False, 'random_crop': True, 'pad_audio': False}
2023-07-10 21:55:11 | INFO | fairseq.models.hubert.hubert | HubertModel Config: {'_name': 'hubert', 'label_rate': 50.0, 'extractor_mode': default, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': gelu, 'layer_type': transformer, 'dropout': 0.1, 'attention_dropout': 0.1, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.1, 'dropout_features': 0.1, 'final_dim': 256, 'untie_final_proj': True, 'layer_norm_first': False, 'conv_feature_layers': '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2', 'conv_bias': False, 'logit_temp': 0.1, 'target_glu': False, 'feature_grad_mult': 0.1, 'mask_length': 10, 'mask_prob': 0.8, 'mask_selection': static, 'mask_other': 0.0, 'no_mask_overlap': False, 'mask_min_space': 1, 'mask_channel_length': 10, 'mask_channel_prob': 0.0, 'mask_channel_selection': static, 'mask_channel_other': 0.0, 'no_mask_channel_overlap': False, 'mask_channel_min_space': 1, 'conv_pos': 128, 'conv_pos_groups': 16, 'latent_temp': [2.0, 0.5, 0.999995], 'skip_masked': False, 'skip_nomask': False, 'checkpoint_activations': False, 'required_seq_len_multiple': 2, 'depthwise_conv_kernel_size': 31, 'attn_type': '', 'pos_enc_type': 'abs', 'fp16': False}
Traceback (most recent call last):
  File "/Users/axelerikswenson/Desktop/Multi-Model-RVC-Inference/app.py", line 344, in <module>
    categories = load_model()
  File "/Users/axelerikswenson/Desktop/Multi-Model-RVC-Inference/app.py", line 135, in load_model
    cpt = torch.load(f"weights/{category_folder}/{character_name}/{model_path}", map_location="cpu")
NameError: name 'model_path' is not defined. Did you mean: 'model_name'?
(base) axelerikswenson@Axels-MBP Multi-Model-RVC-Inference % python app.py
2023-07-10 21:56:49 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-07-10 21:56:49 | INFO | faiss.loader | Successfully loaded faiss with AVX2 support.
没有发现支持的N卡, 使用CPU进行推理
2023-07-10 21:56:49 | INFO | fairseq.tasks.hubert_pretraining | current directory is /Users/axelerikswenson/Desktop/Multi-Model-RVC-Inference
2023-07-10 21:56:49 | INFO | fairseq.tasks.hubert_pretraining | HubertPretrainingTask Config {'_name': 'hubert_pretraining', 'data': 'metadata', 'fine_tuning': False, 'labels': ['km'], 'label_dir': 'label', 'label_rate': 50.0, 'sample_rate': 16000, 'normalize': False, 'enable_padding': False, 'max_keep_size': None, 'max_sample_size': 250000, 'min_sample_size': 32000, 'single_target': False, 'random_crop': True, 'pad_audio': False}
2023-07-10 21:56:49 | INFO | fairseq.models.hubert.hubert | HubertModel Config: {'_name': 'hubert', 'label_rate': 50.0, 'extractor_mode': default, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': gelu, 'layer_type': transformer, 'dropout': 0.1, 'attention_dropout': 0.1, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.1, 'dropout_features': 0.1, 'final_dim': 256, 'untie_final_proj': True, 'layer_norm_first': False, 'conv_feature_layers': '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2', 'conv_bias': False, 'logit_temp': 0.1, 'target_glu': False, 'feature_grad_mult': 0.1, 'mask_length': 10, 'mask_prob': 0.8, 'mask_selection': static, 'mask_other': 0.0, 'no_mask_overlap': False, 'mask_min_space': 1, 'mask_channel_length': 10, 'mask_channel_prob': 0.0, 'mask_channel_selection': static, 'mask_channel_other': 0.0, 'no_mask_channel_overlap': False, 'mask_channel_min_space': 1, 'conv_pos': 128, 'conv_pos_groups': 16, 'latent_temp': [2.0, 0.5, 0.999995], 'skip_masked': False, 'skip_nomask': False, 'checkpoint_activations': False, 'required_seq_len_multiple': 2, 'depthwise_conv_kernel_size': 31, 'attn_type': '', 'pos_enc_type': 'abs', 'fp16': False}
Traceback (most recent call last):
  File "/Users/axelerikswenson/Desktop/Multi-Model-RVC-Inference/app.py", line 344, in <module>
    categories = load_model()
  File "/Users/axelerikswenson/Desktop/Multi-Model-RVC-Inference/app.py", line 135, in load_model
    cpt = torch.load(f"weights/{category_folder}/{character_name}/{model_name}", map_location="cpu")
  File "/Users/axelerikswenson/anaconda3/lib/python3.10/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/Users/axelerikswenson/anaconda3/lib/python3.10/site-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
(base) axelerikswenson@Axels-MBP Multi-Model-RVC-Inference %

**Comment by ArkanDash** [comment]
Unsuccessful model download.

Try redownloading it again.

**Comment by ElhamAhmedian** [comment]
Same here, I have my own trained model. Same error.
