### ISSUE TITLE
How can I fix this?

### ISSUE THREAD

**Issue by Quicksticks-oss** [ArkanDash/Multi-Model-RVC-Inference#2]
Hello I loaded up my model and I try to convert and I get this error.

Traceback (most recent call last):
  File "/home/reaktor/Downloads/Multi-Model-RVC-Inference/app.py", line 101, in vc_fn
    audio_opt = vc.pipeline(
  File "/home/reaktor/Downloads/Multi-Model-RVC-Inference/vc_infer_pipeline.py", line 396, in pipeline
    self.vc(
  File "/home/reaktor/Downloads/Multi-Model-RVC-Inference/vc_infer_pipeline.py", line 216, in vc
    npy = np.sum(big_npy[ix] * np.expand_dims(weight, axis=2), axis=1)
IndexError: index -1 is out of bounds for axis 0 with size 0

**Comment by Quicksticks-oss** [comment]
Fixed I used the training index file instead of the adding index file sry.
